apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trio-demo-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: example-manifests/trio-app/dev
    repoURL: https://github.com/idan-codefresh/promotion-example.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: trio-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
