apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trio-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: trio-app
spec:
  project: default
  source:
    path: example-manifests/trio-app/aperture-dev
    repoURL: https://github.com/idan-codefresh/promotion-example.git
    targetRevision: main
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
